### ISSUE TITLE
Unable to view searches

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#12]
Environment - Pulte New Dev ADS 3.1.7

https://archon-datastore.platform3solutions.com/pulte/dev/login

App : Recruiting Management
Search : Test_Assign

Unable to see the Searches

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/42184278/42e88259-6db1-4b03-bc7f-ebe808a799d3)

**Comment by kilam005** [comment]
Sideeffect of #8 
Permission / Configuration missing.

**Comment by harsha-kotha** [comment]
Issue # 8 is different, This issue i am not able to View any Searches at all.

**Comment by harsha-kotha** [comment]
Issue # 8 is long running Export

**Comment by akhilkottedi** [comment]
we miss the heap size for search service and updated in installation script and updated in github repo.

**Comment by Devikak7** [comment]
this Server related issue is now able to view the Search screen 

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/46775670/697f2660-e78c-40c5-a87f-f18fc28bae70)

**Comment by Udhayanila8** [comment]
This is server related issue , unable to retest. so closed this issue

**Comment by harsha-kotha** [comment]
Let it be server issue, i need to see Root Cause and make sure this does not repeat. Please log what heap size parameter was changed i need details of before and after changes on what was changed to be added to the issue as screenshot,

**Comment by harsha-kotha** [comment]
I still do not see the RCA, can we capture what was the config earlier and what was changed?

**Comment by ClementJosh21** [comment]
@harsha-kotha 



![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/76196584/707355a5-ecc4-459e-b0f8-f5c8743d112d)


As you can see in this image there is an attribute _**'${core_max_heap} '**_ this is a actual heap size set for search service which is 8GB. The RCA for this issue is that the attribute  _**'${core_max_heap} '**_  was replaced as  _**'${max_heap} '**_ , the size of max_heap is 1GB hence there was memory constraint while operating searches.



![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/76196584/626924d4-6c8d-4b43-a06b-13f37a1c2af9)

**Comment by harsha-kotha** [comment]
Thanks
