### ISSUE TITLE
Searches_ While click the nested link, in results shows undefined

### ISSUE THREAD

**Issue by Udhayanila8** [P3-Core-Dev-Team/P3-Q-A#14]
**Server**
Pulte prod

**Module**
Searches

**Steps**

1. Login.
2. Create a search with a nested link.
3. Perform the search
4. Click the link in the results.

**Expected behavior**
The link should be performed.

**Current behavior**
It is showing undefined results.

**Screenshots**
![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/502ff3ed-1870-411e-adcd-a7e1f2146557)

**Comment by Udhayanila8** [comment]
Issue has been fixed. Tested in EMR region.

![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/243d7221-5235-45d8-86bc-49caf3b6ff91)

**Comment by ClementJosh21** [comment]
@harsha-kotha 
**_RCA:_**  When trying to use nested link the schema of the parent search was still in place even after routing to the child search, hence the result obtained will not be matched with the schema of the parent search.

**_Fix Given:_** The parent search schema is cleared and the child search's metadata is updated before routing is done.

_Note: This issue occurred due to certain time delay which might be little difficult to replicate now._

**Comment by kilam005** [comment]
@harsha-kotha 
please check Details in above comments and provide closure.

**Comment by harsha-kotha** [comment]
@Udhayanila8  Please check and close this fix.
