### ISSUE TITLE
FR : ADS-Search Results - Column Ordering

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#146]
ADS - Search results - column re-arranging as per user preference

**Comment by kilam005** [comment]
This will not be supported.
There is a re-ordering ability on the search as they get the results.
Each users can have different need and this cannot be maintained outside our current seatch session maintenance mode.

**Comment by kilam005** [comment]
@raniangamuthu 

Please check and provide updates,
Like mentioned in the previous comment, we have re-ordering ability on the search results which will be confinded to that session.
You may also use Column sets configuration.

Since there is no action possible from our end Issue will be auto closed on 12th Novemeber if no reply or concern is updated

**Comment by raniangamuthu** [comment]
I see we have the re-ordering ability using the column configure option and it works as expected. Post re-ordering the export does not reflect the ordering.

**Comment by kilam005** [comment]
Export and order will not be combined.
We have export option within inline panel too.
This cannot be addressed.

**Comment by kilam005** [comment]
@raniangamuthu please see above comments.
This will not be operatable as its clashed with existing export behavious of the tool.

**Comment by kilam005** [comment]
@raniangamuthu 
reminder to check and provide closure.

**Comment by raniangamuthu** [comment]
we are good to close this as of now
