### ISSUE TITLE
ADS - Login -SSO - Neste

### ISSUE THREAD

**Issue by suseela22** [P3-Core-Dev-Team/P3-Q-A#162]
**Describe the bug**

SSO is not working after the deployment. Deployed build is 2024.09.45542_P4

**Screenshots**

![image](https://github.com/user-attachments/assets/389dfc46-ed84-4750-b563-ad49942a4520)

**Additional context**
Build no : 2024.09.45542_P4
Region : https://neste-dev.platform3solutions.com/
Client : Neste

**Comment by harsha-kotha** [comment]
Please add Corrective action taken to avoid this issue in future.

**Comment by ashoksri0** [comment]
@suseela22  auithentication server and our core services are not in sync with jwt token secrets is what the reason for the issue. we need make the saml and jwt token configuration in database will prevent this issue in future, from end user its a bug i will make this as aenhancement from my sdie and move forward

**Comment by abirami1994** [comment]
RCA:
the signkey was set in application.yml in all the services.Since the sign key was different in auth service application.yml this issue occured


FIX PROVIDED:
scheduler is added to automatically generate new sign in key every 3 months so the need to maintain the sign key in application.yml is removed

**Comment by suseela22** [comment]
Working as expected
