### ISSUE TITLE
ADS - Pulte Prod Services going down frequently

### ISSUE THREAD

**Issue by harsha-kotha** [P3-Core-Dev-Team/P3-Q-A#19]
Last 1 week we have seen Pulte Services going down several times. The most recent is on 16th Sep IST Time 7.20 AM to 8.20 AM.

"ADS Core Service is down please check the pulte-prod env"

@akhilkottedi has restarted services and acknowledged to provide RCA.

**Comment by harsha-kotha** [comment]
ADS Core Service is down please check the pulte-prod env

Alert : Wed 20-09-2023 10:05 and Wed 20-09-2023 10:10

Reported in the group @akhilkottedi  acknowledged to check root cause.

**Comment by kilam005** [comment]
@akhilkottedi any update for this?

@harsha-kotha i've lost track on this. can you help on the issue

**Comment by harsha-kotha** [comment]
@akhilkottedi  Please check, as far as i know we only knew the services went down and we got automated email notification.

**Comment by akhilkottedi** [comment]
Configuration issue for core service java max heap size mention 2gb but we need to mention 8gb, we have changed the heap size upto 8gb after that services running properly.

**Comment by harsha-kotha** [comment]
How do we know that 8 GB is sufficient? Please share RCA on why earlier configuration was not sufficient.

**Comment by selvakumarchandran** [comment]
@harsha-kotha Typically, the heap size for the Kafka utility server is configured to be 8 GB. Consequently, all Kafka messages are loaded into the core services. Therefore, the heap size for the core services also needs to be 8 GB. Otherwise, if the message upload into Kafka fails, the core service also go down.

**Comment by kilam005** [comment]
`RCA`
Our previous versions did not follow best practices wen dealing with Kakfa and the queue used to quickly get consumed to its max and so the configured heap was insufficient.

`Fix details`
@ashoksri0 & team did full recheck of code where kafka gets involved to handle all incorrect practices. The configuration was also tuned to handle the queue correctly.

**Comment by harsha-kotha** [comment]
My worry is how do we say 8 GB is sufficient. What if we run into same issue with 8 GB what options do we have? we cannot just keep increasing more.

**Comment by kilam005** [comment]
@rajesh-jeyaraman 
i've been asking Selva for almost 2 months to provide comments and close this.
Please allocate some time for him to collect any data if needed to bring this to full closure

**Comment by selvakumarchandran** [comment]
Performed testing with a 2 GB heap space, ingested 75 GB to 150 GB of data, and executed 10 to 15 searches around 100 GB of data simultaneously. The services are running without downtime. There is no need to increase the RAM size

**Comment by kilam005** [comment]
@harsha-kotha,

We have done the requied checks by reducing the heap space to (2 GB instead of 8) and trialed execution and simulation of possibile case that can bring the core service down. The current configuration and code has been optimized and garanteed to work without the need to increase beyond the 8 GB limit.

Also the issue is not happening now. 
I think the team has done all possible options to check and confirm the tool is now stable to operate.

please check the notes above and provide a closure, unless you have any specific case you want us to verify and provide details.

**Comment by harsha-kotha** [comment]
We shall monitor and see if this is helpful. Closing the issue.
