### ISSUE TITLE
ADS-Search - When the search result field is hidden and if it is a link field to nested search it is still visible in the breadcrumb (Dell)

### ISSUE THREAD

**Issue by kilam005** [P3-Core-Dev-Team/P3-Q-A#50]
When the search result field is hidden and if it is a link field to nested search it is still visible in the breadcrumb

![image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/18091138/67563606-cc71-4b00-9d26-0244e5e86937)

This is internal as well as part of Dell issues.

**Comment by kilam005** [comment]
The UI and BE team (@prabhakaranUI and @ClementJosh21) were informed of this and ideation was completed. 
It should be soon implemented.

**Comment by ClementJosh21** [comment]
@kilam005 The ideation is completed but we are yet to start the actual implementation. Will inform once the we start the actual implementation.

**Comment by ClementJosh21** [comment]
@kilam005 The development and unit testing is completed. The PR is in review state.

**Comment by Udhayanila8** [comment]
Version: 2024.03.45398
Server: 192.168.56.146
Enable the mask field and create the link
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/056556b3-d6c1-47df-9d60-0aef7e1ae4a5)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/fc247176-000c-4d73-81d4-59d0115f0d30)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/aa80bb5c-6b52-4767-b094-b6bcd01c8377)
Create nested link for another search, on that search the given column is hidden in their search form
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/1f25850d-0a49-4560-a49a-80ca2f0abf8a)
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/d0cbb6db-35f1-4abb-92de-f6d26bab84e7)
Payload not passing because that is hidden field in that search
![Image](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/82999693/73fcbab2-2405-44b1-8e93-d8298b6ff8e9)

**Comment by kilam005** [comment]
@ClementJosh21 Is this released already?
If not released in which version will it go out?

**Comment by kilam005** [comment]
Rani can you please check this fix and provide closure?

**Comment by raniangamuthu** [comment]
Accepted and closing this for now

**Comment by kilam005** [comment]
Based on above comment marking this item closed
