### ISSUE TITLE
ADS-Search - Configure columns > Reflect in Filter options (Dell)

### ISSUE THREAD

**Issue by raniangamuthu** [P3-Core-Dev-Team/P3-Q-A#78]
Execute Search > Search results page - configure columns to make a column invisible > Go to Filter options - Advanced Filter still shows the invisible column to be filtered which is not expected as it configured to be hidden.
![Screenshot 2024-02-11 125830](https://github.com/P3-Core-Dev-Team/P3-Q-A/assets/69497085/7b339e46-50bc-42fe-a472-ac16e49e64c1)

**Comment by kilam005** [comment]
@raniangamuthu 
will connect and get more details on this.
This can be taken up in next dev sprint cycle only after 3.1.8 release

**Comment by kilam005** [comment]
@maheswarareddyi or  @saumyaguptaa work with @raniangamuthu to get the needs documented

**Comment by kilam005** [comment]
@maheswarareddyi has planned to get details from @raniangamuthu  this week.

**Comment by maheswarareddyi** [comment]
@raniangamuthu Please review the following requirements to ensure they meet your expectations. Feel free to add additional points if needed

**Current behaviour:** 
In the current ADS system, the users can view and add filter conditions for the fields that are hidden in the search result screen.

**Expected behaviour:**
The system shouldn't allow the users to apply filter conditions for the field that was hidden in the search results using the column configuration option.

- Hide the result field if the check box of a field is unchecked in the result set column configurations
- If the hiding fields are not supported, disable the fields with a tooltip "The field was hidden in the result set, so it cannot be used to filter the results"
- When displaying a result set with a field filter option, if the user attempts to hide a field that was used in the filter condition, the system must prompt the user to reset the result set before the field can be hidden. This is because the displayed results were generated using the selected field as a filter condition
- Display the following text in the action proceed confirmation prompt "Hiding the field '<field name>' will reset the search results, as the results were fetched using this field as a filter. Do you still want to proceed?".

**Comment by raniangamuthu** [comment]
As discussed, we prompt to get the confirmation from the user on the action right. Looks good to me to proceed @maheswarareddyi

**Comment by ElakkiyaBalasubramanian10** [comment]
@kilam005 @ClementJosh21 @prabhakaranUI Have to review the requirements and provide confirmation.

**Comment by kilam005** [comment]
yet to review and will be taken up once other ongoing items are cleared

**Comment by kilam005** [comment]
Requirements are reviewed and no question at this point. To be taken up for development next week.

**Comment by kilam005** [comment]
Development yet to start

**Comment by prabhakaranUI** [comment]
Development in progress

**Comment by ClementJosh21** [comment]
@kilam005  BE and FE development is completed. Unit testing is going on.

**Comment by ClementJosh21** [comment]
@kilam005  PR in review state. Yet to be merged.

**Comment by prabhakaranUI** [comment]
@kilam005 code merged and waiting for deployment

**Comment by ayyandurai-madhes** [comment]
Deployed in test region (146)
version : 2024.07.45502_RC5

**Comment by Udhayanila8** [comment]
**_Server: 192.168.56.146
Version: 2024.08.45507_RC5_**

Hidden the column in column settings,
![image](https://github.com/user-attachments/assets/6eaaeb37-44f6-4c81-a16e-0023b1f294f5)
![image](https://github.com/user-attachments/assets/74b29271-fda4-4c19-85ab-1cedfb8f6755)
Customized the column to be hidden in the result page.
![image](https://github.com/user-attachments/assets/d3c1e663-29ac-4de3-b64d-3395dc1f6fc8)
The customized column doesn't show in the filter option, but the hidden field is disabled with the tooltip
![image](https://github.com/user-attachments/assets/640a1f18-878b-4eef-afa7-1e1453df09c6)

**Comment by maheswarareddyi** [comment]
@raniangamuthu This feature is available in ADS v2024.09.45542 on the 218 server in Chennai DC.
Please check and confirm the working and provide closure to this feature.

**Comment by maheswarareddyi** [comment]
@raniangamuthu Could you please provide the verification status of this feature? If no update is received from your end by October 21, 2024, the feature will be marked as closed.

**Comment by raniangamuthu** [comment]
verified
